syntaxes/effekt.tmLanguage.json
- parse comments precisely
- support splices in (currently all) strings
- support individual characters
- support escapes in strings and characters
- support multi-line strings
- support namespace declarations
- parse capability sets precisely
- add folding markers
- support float literals
- parse typed holes in line with the rest of the file
- add operator support (only visible in some themes)
- `in` is now a conditional keyword (rendered as a keyword only in `var x in r = ...`)
- fix definitions being stuck at `=>` and then not parsing the rest of the arguments
- highlight `at` correctly
- highlight invalid escapes
- highlight `module`s and `import`s correctly
- add support for `region`
- currently, we only highlight `'\uA0EB'` char literals as opposed to `\uA0EB` detected in the …
=> Improve syntax highlighting

.github/workflows/deploy.yml
Resolves #21
**Untested**, needs `VSCE_PAT` (a personal access token for publishing an extension, see [here](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token))
=> CI: Deploy to the VSCode marketplace

package.json
`npm version major/minor/patch` can change the version of the currently developed `npm` package:
- by bumping major/minor/patch in `package.json`
- making a commit
- and a `git tag`
... which makes it very nice to use to make a deploy using a single command.
Unfortunately, it reformats the `package.json` file into a more standard version. It's still 4 spaces, but a bit more verbose.
I think the trade-off is worth it here, just to make releasing a bit easier.
I ran `npm version patch` and only selectively added the things that do _not_ change the version, thus making the diff smaller for an actual release.
=> Reformat package.json for npm

.github/workflows/ci.yml, .github/workflows/deploy.yml, .vscode/extensions.json, .vscode/launch.json, .vscode/settings.json, .vscode/tasks.json, package-lock.json, package.json, src/effektManager.ts, src/extension.ts, src/semver.d.ts
This is a somewhat rough draft of an automatic installer & updater for Effekt (addresses https://github.com/effekt-lang/effekt/issues/289)
I **cannot** test this locally, my local setup is quite weird and I can't really use `npm` for Effekt distribution.
This PR will require **extensive** testing on various platforms.
- new status bar shows the state of the LSP server, current Effekt version and the selected backend (useful for debugging)
- clicking on the status bar checks for Effekt updates (in `npm`)
- updated dependencies to allow newer VSCode features
- on startup, check if we can find the `effekt` binary:
- if not and if it's a custom executable by the user, report a specific error
- if not, offer the user to install the newest version of Effekt from `npm`
- if we have `effekt`, …
=> Effekt Version Manager: automatic installer and updater

language-configuration.json
Closes issue #19 by continuing `//` and `///` single-line comments automagically.
Except that it's not configurable. That's due to our choice of using a static `language-configuration.json`.
=> Continue single-line comments after pressing enter

src/effektManager.ts, src/extension.ts
Addresses the `main` (haha!) part of #12 by adding "Run" options over `def main()`, that opens up a REPL, imports a file, and runs it:
---
How does it work?
- search for functions that look like `def main() =`
- if it finds one, create a code lens for the URI/file it is in
- clicking run creates a REPL terminal (if it doesn't exist for that file already), imports the file and runs `main`
The code still needs heavy refactoring and a bit of testing, this is just a proof of concept born out of frustration.
---
**TODO:**
=> Code lens for running `main`

src/effektManager.ts
I was missing some visual feedback when pressing the Effekt button in the status bar when the Effekt version is up-to-date. This is how it looks like after this PR:
=> Show info popup when Effekt is up-to-date

src/effektManager.ts
This PR adds a feature to the Effekt version update flow. After successfully updating the Effekt version, the user is prompted with an option to view the changelog for the new version. If the user chooses "Yes," their browser will open to the changelog page for the respective version on GitHub
- Modified the `promptForAction` method to offer the user the option to view the changelog after an successfull update.
- If the user accepts, it opens the changelog URL in their default browser.
1. Run the extension in debug mode (`F5`).
2. Press Yes when prompted to update your Effekt version
3. When the update/install completes, a prompt will appear asking if you want to view the changelog.
4. Clicking "Yes" should open the changelog page in your browser.
- #42: Provide changelog link after …
=> Add changelog link prompt after Effekt update

.git-blame-ignore-revs, .github/workflows/ci.yml, .prettierrc, eslint.config.mjs, package-lock.json, package.json, src/effektLanguageClient.ts, src/effektManager.ts, src/extension.ts, src/inlayHintsProvider.ts, src/irProvider.ts
This PR introduces 
- ESLint as a linter (`npx eslint .`  or  `npm run lint `  and `npm run lint:fix`  to lint or lint&fix all files at once)
- Prettier as a formatter (`npm run format` and `npm run format:check`) 
The CI performs `npm run lint` and `npm run format:check`
resolves #73
=> Add ESLint and Prettier as linter and formatter

src/extension.ts
Screenshot:
Before, the `def main()` in `examples` would _not_ have a `|> Run` button because of the indentation, but we have programs that look like this, so I do want to support it :)
---
Motivation extracted from #12:
> The regex for finding `main` could be tweaked: it's also fine to show the `|> Run` button for:
> ```scala
> def myFunction(): Int = 42
> 
> namespace examples { 
>   def main() = println(myFunction())
> }
> ```
> which is currently not shown, since the regex doesn't account for leading whitespace:
> 
> https://github.com/effekt-lang/effekt-vscode/blob/07b504c52fbdb5560b40ebc48e181944fdb17aa1/src/extension.ts#L82
=> Allow running indented 'main'

.gitignore, .vscode/launch.json, .vscode/tasks.json, .vscodeignore, esbuild.js, eslint.config.mjs, package-lock.json, package.json
Resolves #37 
Just adding a `.vscodeignore` reduces the package size from 500K to 70K. :)
We _could_ also use ESBuild as per the official tutorial https://code.visualstudio.com/api/working-with-extensions/bundling-extension#using-esbuild, but I don't know how much it would actually help...
Feel free to make that into a separate issue if you care, dear reader :)
=> Bundle extension properly

src/effektManager.ts
Fixes #72 by printing a more useful message.
If Effekt can be found locally:
if it can't:
=> Handle failure to communicate with npm gracefully

src/holesPanel/holes.css
Before, the `.css` used `... terminal-Ansi-Blue` and `... terminal-Ansi-Green` for terms and types in the panel, which looked off in some themes. This simple fix would change the term and type colors to be the foreground color of the current theme. This ensures readability while not hard coding colors.
=> Fix colors in Holes panel

src/extension.ts, src/holesPanel/effektHoleInfo.ts, src/holesPanel/holes.css, src/holesPanel/holesViewProvider.ts, src/holesPanel/holesWebView.ts
Allow focusing the hole at the cursor position (no hovering [ yet? ] ) for navigation between code and the holes panel.
[Screencast from 2025-06-04 13-20-06.webm](https://github.com/user-attachments/assets/0c63a142-6b35-4cf8-978f-f24112ba70d9)
=> Focus holes on editor navigation

src/extension.ts
Unifies the format between `didChangeConfiguration` requests and `initializationOptions`.
=> Send init options under "effekt" key

src/holesPanel/effektHoleInfo.ts, src/holesPanel/holesWebView.ts
Previously, term bindings were not properly distinguished from type bindings in the schema (`effektHoleInfo.ts`).
=> Distinguish term from type bindings

src/extension.ts
Resolves #105
This PR removes the `await` from the `handleEffektUpdates()` function to stop it from blocking the lsp init
=> Stop update prompt from blocking the holes panel

src/holesPanel/webview/BindingsSection.tsx
In addition to fuzzy search, this PR enables prefix search in `MiniSearch`. This means that typing `pri` will show `println`. Previously, it would not, because the edit distance to `println` was to large (which is configured with the `fuzzy` parameter.
=> Use prefix search

.github/workflows/ci.yml, .github/workflows/deploy.yml, package.json
To fix the CI, we require a node version of 20.x or higher
=> Require node >= 20.x

src/holesPanel/holesViewProvider.ts, src/holesPanel/webview/BindingsSection.tsx, src/holesPanel/webview/HoleCard.tsx, src/holesPanel/webview/HolesPanel.tsx
This PR introduces the ability to deselect (close) a highlighted hole in the panel, make it simple to scroll and navigate through a panel with many holes, as the  user is not forced to scroll thorugh the complete (long) bindingslist to get to the next hole
=> Deselecting holes

src/holesPanel/effektHoleInfo.ts, src/holesPanel/webview/BindingItem.tsx, src/holesPanel/webview/BindingsSection.tsx
Display unified signature information rather than making a distinction between type and term bindings.
=> Use signature field on BindingInfo

esbuild.js, package-lock.json, package.json, src/extension.ts, src/holesPanel/holesViewProvider.ts, src/holesPanel/webview/HoleCard.tsx, src/holesPanel/webview/holes.css, src/holesPanel/webview/holesPanel/index.tsx, src/holesPanel/webview/holesPanel/useHolesPanelState.ts, src/holesPanel/webview/index.tsx, src/holesPanel/webview/messages.ts, src/holesPanel/webview/vscodeApi.ts, src/mcp/app.ts, src/mcp/docIndexer.ts, src/mcp/effekt.instructions.md, src/mcp/holeListener.ts, src/mcp/index.ts, src/mcp/lspClient.ts, src/mcp/tools/holeById.ts, src/mcp/tools/index.ts, src/mcp/tools/listHoles.ts, src/mcp/tools/searchStdlib.ts, src/mcp/tools/types.ts, src/mcpManager.ts, tsconfig.base.json
Adds an initial MCP prototype to the VSCode extension. It is hidden behind a configuration option marked as experimental.
The MCP server implementation is shipped with the VSCode extension and is launched on extension activation and stopped on extension deactivation.
The MCP server listens to a local HTTP server on a fixed port. This allows us to statically configure the MCP server with VSCode once. If we were to use stdio transport, the path in the MCP server configuration would have to change with each update, so after each extension update, we would have to re-prompt the user to update the configuration.
The downside of the current implementation is that there can only ever be one instance of the MCP server. If a user has multiple windows open, the first opened window controls the …
=> MCP Prototype

src/holesPanel/webview/BindingItem.tsx, src/holesPanel/webview/BindingsSection.tsx, src/holesPanel/webview/ScopeGroup.tsx
Previously, when pressing down the up/down arrow keys, rapidly changing the selected binding caused visible stutters. This PR fixes these performance issues using memoization to prevent unnecessary recomputation of the binding lists and unnecessary rerendering of the corresponding React components.
On my machine, this resolves any observable performance issues.
=> Improve performance of hole bindings selection change
